openapi: 3.0.3
info:
  title: Webpage Analyzer API
  description: API for analyzing webpages and extracting specific metadata including HTML version, page title, headings, links, and login forms
  version: 1.0.0
  contact:
    name: Webpage Analyzer Team
servers:
  - url: http://localhost:8990
    description: Development server
  - url: https://api.webpage-analyzer.com
    description: Production server

paths:
  /api/health:
    get:
      summary: Health check
      description: Check if the service is running
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  service:
                    type: string
                    example: "webpage-analyzer"
                required:
                  - status
                  - service

  /api/analyze:
    post:
      summary: Analyze webpage
      description: Analyze a webpage and return specific information including HTML version, page title, headings, links, and login form detection
      tags:
        - Analysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: URL of the webpage to analyze
                  example: "https://example.com"
              required:
                - url
      responses:
        '200':
          description: Analysis completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebpageAnalysis'
        '400':
          description: Invalid request or webpage not reachable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to analyze webpage"

  /api/status:
    get:
      summary: Get service status
      description: Get the current status and capabilities of the analysis service
      tags:
        - System
      responses:
        '200':
          description: Service status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Service is running and ready for webpage analysis"
                required:
                  - status

components:
  schemas:
    WebpageAnalysis:
      type: object
      description: Result of webpage analysis
      properties:
        url:
          type: string
          format: uri
          description: URL that was analyzed
          example: "https://example.com"
        html_version:
          type: string
          description: HTML version of the document
          example: "HTML5 (implied)"
        page_title:
          type: string
          description: Page title from the title tag
          example: "Example Domain"
        headings:
          type: object
          description: Count of headings by level (h1, h2, h3, etc.)
          additionalProperties:
            type: integer
          example:
            h1: 1
            h2: 3
            h3: 5
        internal_links:
          type: integer
          description: Number of internal links (relative URLs)
          example: 15
        external_links:
          type: integer
          description: Number of external links (absolute URLs)
          example: 8
        inaccessible_links:
          type: integer
          description: Number of inaccessible links
          example: 0
        has_login_form:
          type: boolean
          description: Whether the page contains a login form
          example: false
        analyzed_at:
          type: string
          format: date-time
          description: When the analysis was performed
          example: "2024-01-15T10:30:00Z"
        processing_time:
          type: string
          format: duration
          description: Time taken to process the analysis
          example: "150ms"
      required:
        - url
        - html_version
        - page_title
        - headings
        - internal_links
        - external_links
        - inaccessible_links
        - has_login_form
        - analyzed_at
        - processing_time

    AnalysisError:
      type: object
      description: Error response when webpage analysis fails
      properties:
        status_code:
          type: integer
          description: HTTP status code of the failed request
          example: 404
        error_message:
          type: string
          description: Detailed error message
          example: "HTTP 404: Not Found"
        url:
          type: string
          format: uri
          description: URL that failed to analyze
          example: "https://nonexistent.example.com"
      required:
        - status_code
        - error_message
        - url

tags:
  - name: Analysis
    description: Webpage analysis operations
  - name: System
    description: System health and status operations 